
BASE_ID = 0
ID_MAIN_FRAME = BASE_ID + 1
ID_NOTEBOOK_RUNJOB = BASE_ID + 2
ID_NOTEBOOK_DELETEJOB = BASE_ID + 3
ID_NOTEBOOK_MACHINE = BASE_ID + 4
ID_LOGIN_DIALOG = BASE_ID + 5


ID_CONFIG_JOB = BASE_ID + 20

BASE_MENU = BASE_ID+40
ID_MENU_MACHINE = BASE_MENU + 1
ID_MENU_CHANGE_PIN = BASE_MENU + 2
ID_MENU_ADD_LOCAL = BASE_MENU + 3
ID_MENU_ADD_JOB = BASE_MENU + 4
ID_MENU_DELETE_JOB = BASE_MENU + 5
ID_MENU_EXIT = BASE_MENU + 6
ID_MENU_DELETE_FILE = BASE_MENU + 7


